from pygame import Vector2
from src.Levels import Levels

class GameConfig:
    SCREEN_DIMENSION = Vector2(800, 600)
    WINDOW_NAME = "Flappy Brain"
    REFRESH_RATE = 60
    INITIAL_SCROLL_SPEED = 0.01 * SCREEN_DIMENSION.x
    GROUND_SPACE = 50 * SCREEN_DIMENSION.y / 400
    DEFAULT_LEVEL = Levels.MENU
    GRAVITY_FORCE = 3000
    MENU_FONT_TILE_SIZE = 40
    MENU_FONT_P_SIZE = 20
    FONT = 'assets/policeFlappy.ttf'
    FONT_COLOR = (255, 255, 255)
    FONT_COLOR_SECONDARY = (0, 0, 0)
    FLAP_ANIMATION_TIMING = 100
    PIPES_BUFFER = 40
    MAX_SCROLL_SPEED_AUGMENTATIONS = [1, 2, 5]
    SCROLL_SPEED_AUGMENTATIONS = [0.1, 0.2, 0.4]
    DIFFICULTY_COEFFICIENTS = [0.1, 0.2, 0.3]
    MAX_DIFFICULTY_COEFFICIENTS = [1, 2, 5]
    SCORES_DIFFICULTY_CHECKPOINTS = [1, 1, 1]
    SCREEN_DIMENSION_DIFFICULTY_INCREASE = SCREEN_DIMENSION.x / 750