from pygame import Vector2

from src.DisplayModes import DisplayModes
from src.Levels import Levels

class GameConfig:
    DEFAULT_DISPLAY_MODE = DisplayModes.FULLSCREEN
    DEFAULT_SCREEN_DIMENSIONS = Vector2(1200, 800)
    SCREEN_DIMENSION = DEFAULT_SCREEN_DIMENSIONS
    WINDOW_NAME = "Flappy Brain"
    REFRESH_RATE = 60
    FULLSCREEN_SCROLL_SPEED = 10
    SMALL_SCREEN_SCROLL_SPEED = 5
    SCROLL_SPEEDS = { 0: 3, 1000: 4, 1500: 6, 1750: 8, 1920: 10, 2120: 12, 2440: 15}
    INITIAL_SCROLL_SPEED = FULLSCREEN_SCROLL_SPEED
    GROUND_SPACE = 50 * SCREEN_DIMENSION.y / 400
    DEFAULT_LEVEL = Levels.MENU
    GRAVITY_FORCE = 3000
    MENU_FONT_TILE_SIZE = 40
    MENU_FONT_P_SIZE = 20
    FONT = 'assets/policeFlappy.ttf'
    FONT_COLOR = (255, 255, 255)
    FONT_COLOR_SECONDARY = (0, 0, 0)
    BACKGROUND_OVERLAY_DARKNESS = 64
    FLAP_ANIMATION_TIMING = 100
    PIPES_BUFFER = 40
    MAX_SCROLL_SPEED_AUGMENTATIONS = [2, 3, 6]
    SCROLL_SPEED_AUGMENTATIONS = [0.05, 0.1, 0.5]
    DIFFICULTY_COEFFICIENTS = [0.1, 0.2, 0.3]
    MAX_DIFFICULTY_COEFFICIENTS = [2, 4, 8]
    SCORES_DIFFICULTY_CHECKPOINTS = [1, 1, 1]