name: Build and Deploy with Pygbag

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygbag
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build with Pygbag
      run: |
        python -m pygbag --build --ume_block 0 main.py

    - name: Copy build files to temporary directory
      run: |
        mkdir -p /tmp/flapeeg-build
        cp -r build/web/* /tmp/flapeeg-build/

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: VillyGH/WBL-WebApp
        token: ${{ secrets.WEBAPP_PUSH_TOKEN }}
        path: webapp
        fetch-depth: 0

    - name: Set up target branch and copy files
      working-directory: webapp
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b flapeeg-game-update-$(date +%Y%m%d%H%M%S)
        mkdir -p flapeeg
        cp -r /tmp/flapeeg-build/* flapeeg/
        git add flapeeg/
        git commit -m "Update Flapeeg game assets" || echo "No changes to commit"

    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.WEBAPP_PUSH_TOKEN }}
      working-directory: webapp
      run: |
        BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD)
        git push -u origin $BRANCH_NAME
        gh pr create \
          --title "Update Flapeeg game assets" \
          --body "This PR updates the Flapeeg game assets with the latest build from the main repository." \
          --base main \
          --head $BRANCH_NAME \
          --repo VillyGH/WBL-WebApp