name: Build and Deploy with Pygbag

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        path: source

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygbag
        if [ -f source/requirements.txt ]; then pip install -r source/requirements.txt; fi

    - name: Build with Pygbag
      working-directory: source
      run: |
        python -m pygbag --build --ume_block 0 main.py

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: VillyGH/WBL-WebApp
        token: ${{ secrets.WEBAPP_PUSH_TOKEN }}
        path: webapp
        fetch-depth: 0

    - name: Copy build files to target repository
      run: |
        mkdir -p webapp/flapeeg
        cp -r source/build/web/* webapp/flapeeg/

    - name: Commit and Push to WBL-WebApp Repository
      working-directory: webapp
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b flapeeg-game-build
        git add flapeeg/
        git commit -m "Update game assets from Flapeeg Pygame project" || echo "No changes to commit"
        git push -f origin flapeeg-game-build