name: Build and Deploy with Pygbag

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v3
      with:
        path: source

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pygbag
        if [ -f source/requirements.txt ]; then pip install -r source/requirements.txt; fi

    - name: Build with Pygbag
      working-directory: source
      run: |
        python -m pygbag --build --ume_block 0 main.py

    - name: Checkout target repository
      uses: actions/checkout@v3
      with:
        repository: VillyGH/WBL-WebApp
        token: ${{ secrets.WEBAPP_PUSH_TOKEN }}
        path: webapp
        fetch-depth: 0

    - name: Copy build files to target repository
      run: |
        mkdir -p webapp/flapeeg
        cp -r source/build/web/* webapp/flapeeg/

    - name: Add files and git config
      working-directory: webapp
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b flapeeg-game-build
        git add flapeeg/
        git pull
        git push --set-upstream origin flapeeg-game-build

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.WEBAPP_PUSH_TOKEN }}
        commit-message: Update game assets from Flapeeg Pygame project
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: example-patches
        delete-branch: true
        base: master
        title: "Update assets from flapeeg"